language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: composer test

matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5
    - php: 5.6
  fast_finish: true

notifications:
  email:
    recipients:
      - apietka@future-processing.com
      - mwojcik@future-processing.com
    on_success: change
    on_failure: always